# Generated by Django 4.2.1 on 2023-06-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_rating_comment_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'List', 'verbose_name_plural': 'Lists'},
        ),
    ]
