# Generated by Django 4.2.1 on 2023-07-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_location_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='category',
        ),
        migrations.DeleteModel(
            name='PlaceCategory',
        ),
    ]
