# Generated by Django 4.2.1 on 2023-07-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_remove_location_category_delete_placecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='places_images'),
        ),
    ]
