# Generated by Django 4.2.1 on 2023-07-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_location_photo_6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='places_images'),
        ),
    ]
