# Generated by Django 4.2.1 on 2023-08-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_remove_location_city_remove_location_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
