# Generated by Django 4.2.1 on 2023-08-09 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_remove_location_address_location_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='photo_6',
        ),
    ]
