# Generated by Django 4.2.1 on 2023-07-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_interest_remove_profile_followers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='name',
            new_name='img',
        ),
        migrations.AddField(
            model_name='interest',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
