# Generated by Django 4.2.1 on 2023-08-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
