# Generated by Django 4.2.1 on 2023-08-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_name_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tiktok',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
