# Generated by Django 4.2.1 on 2023-08-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_instagram_alter_profile_paypal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='list_import_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
