# Generated by Django 4.2.1 on 2023-08-17 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularlists',
            name='pin',
            field=models.ForeignKey(help_text='Click help icon to search for your pin.', on_delete=django.db.models.deletion.CASCADE, to='places.location', unique=True),
        ),
    ]
