# Generated by Django 4.2.1 on 2023-08-14 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_remove_location_photo_6'),
        ('about', '0002_alter_sections_options_alter_team_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='order',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='order',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='PopularLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.location')),
            ],
            options={
                'verbose_name': 'Popular List',
                'verbose_name_plural': 'Popular Lists',
            },
        ),
    ]
