# Generated by Django 4.2.1 on 2023-08-14 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_remove_location_photo_6'),
        ('about', '0004_alter_popularlists_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularlists',
            name='pin',
            field=models.ForeignKey(help_text='Click help icon to search for your pin.', on_delete=django.db.models.deletion.CASCADE, to='places.location', unique=True),
        ),
    ]
